name: Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t devops-app .
    
      
      
    - name: Login & Push
      run: |
       echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
       docker tag devops-app ${{ secrets.DOCKER_USERNAME }}/devops-app:latest
       docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:latest


